### ISSUE TITLE
UtcOffset control issues 

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#133] opened 2016-09-06 19:08 UTC
Three minor issues.
1. The up/down arrows shows a blank when first pressed. 
   For example, I loaded an image set which shows a UtcOffset of -6.
   When I first click either of the up or down arrows on the UtcOffset control, it shows a blank.
   When I click the up/down arrow a second time, it then shows 00:00, after which I can increment/decrement it.
2. The UtcOffset control shows  :00 after the hours, but there doesn't appear to be any way to set that. There are places with a half hour offset (.e.g, Newfoundland, Canada).  
3. The UtcOffset control uses unfamiliar language to most users. Is it perhaps possible to replace this with the term "Time Zone", and include usual scrollable list? The effect should be identical...
   e.g., a typical menu item in the Microsoft TimeZone drop down (see the control panel) displays :
    (UTC-07:00) Mountain Time (US & Canada)

**Comment by twest820** [comment] 2016-09-09 22:25
Resolved in offline discussion.
1. Duplicate of #123.
2. This is supported.
3. Requires a significant increase in UX complexity and adding TimeZone plus possibly an additional column to the database.  Deferred for now, can be revisited if there's user demand.

**Closed as completed by twest820** 2016-09-09 22:25 UTC
Labels: low priority fix
